cliente_index:
    path:     /
    defaults: { _controller: "PolizasBundle:Cliente:index" }
    methods:  GET

cliente_show:
    path:     /{idcliente}/show
    defaults: { _controller: "PolizasBundle:Cliente:show" }
    methods:  GET

cliente_new:
    path:     /new
    defaults: { _controller: "PolizasBundle:Cliente:new" }
    methods:  [GET, POST]

cliente_edit:
    path:     /{idcliente}/edit
    defaults: { _controller: "PolizasBundle:Cliente:edit" }
    methods:  [GET, POST]

cliente_delete:
    path:     /{idcliente}/delete
    defaults: { _controller: "PolizasBundle:Cliente:delete" }
    methods:  DELETE
